using LabelForge.Core.Media;

namespace LabelForge.Tests;

public sealed class StockCatalogTests
{
    /// <summary>
    /// The catalog is generated by scripts/export_stock_catalog.py from a SQLite file that
    /// is not in this repository, so nothing else would notice an export that went wrong.
    /// A regeneration that silently produced half the media, or none, would look exactly
    /// like a working build until somebody searched for a part number that used to be
    /// there.
    ///
    /// These numbers are a tripwire, not a specification. If a regeneration legitimately
    /// changes them, update them here and say so in the commit; if it changes them without
    /// anybody intending it, that is what this exists to catch.
    /// </summary>
    [Fact]
    public void All_HasExactlyTheEntriesTheLastExportProduced()
    {
        Assert.Equal(797, StockCatalog.All.Count);

        // The two flags most likely to be lost by a column rename in the exporter, and the
        // ones the designer reads: a die-cut radius and a continuous roll both change what
        // the canvas draws.
        Assert.Equal(719, StockCatalog.All.Count(m => m.RadiusMm > 0));
        Assert.Equal(57, StockCatalog.All.Count(m => m.Continuous));
    }

    /// <summary>Every entry has the two fields a picker cannot work without. An export
    /// that dropped a column would still parse and would still count, and would leave a
    /// list of blanks.</summary>
    [Fact]
    public void All_EntriesAreNamedAndDescribed()
    {
        Assert.All(StockCatalog.All, media =>
        {
            Assert.False(string.IsNullOrWhiteSpace(media.PartNumber));
            Assert.False(string.IsNullOrWhiteSpace(media.SizeText));
        });
    }

    [Fact]
    public void All_EntriesHaveSaneData()
    {
        Assert.All(StockCatalog.All, media =>
        {
            Assert.False(string.IsNullOrWhiteSpace(media.PartNumber));
            Assert.False(string.IsNullOrWhiteSpace(media.Material));
            Assert.InRange(media.WidthMm, 1, 400);
            Assert.InRange(media.HeightMm, 1, 400);
            Assert.InRange(media.RadiusMm, 0, 10);
        });
    }

    [Fact]
    public void All_HasNoDuplicatePartNumberAndSizePairs()
    {
        var keys = StockCatalog.All
            .Select(m => (m.PartNumber.ToUpperInvariant(), m.WidthMm, m.HeightMm));
        Assert.Equal(StockCatalog.All.Count, keys.Distinct().Count());
    }

    [Fact]
    public void Search_FindsAKnownPartNumber()
    {
        var results = StockCatalog.Search("3007301-T");

        var media = Assert.Single(results);
        Assert.Equal(75.4, media.WidthMm, 3);
        Assert.True(media.Continuous, "a 20 m receipt roll must be flagged continuous");
    }

    [Fact]
    public void Search_CombinesTermsAcrossFields()
    {
        var results = StockCatalog.Search("z-select 4000d");

        Assert.NotEmpty(results);
        Assert.All(results, m => Assert.Contains("4000D", m.Material, StringComparison.OrdinalIgnoreCase));
    }

    [Fact]
    public void Search_IsEmptyForBlankOrUnmatchedQueries()
    {
        Assert.Empty(StockCatalog.Search("   "));
        Assert.Empty(StockCatalog.Search("no-such-part-number-xyz"));
    }

    [Fact]
    public void Search_HonorsTheLimit()
    {
        Assert.Equal(5, StockCatalog.Search("Z-", limit: 5).Count);
    }
}
