using System.Text.Json;

namespace LabelForge.Core.Media;

/// <summary>
/// Catalog of official Zebra media specifications, loaded once from an embedded
/// JSON resource (regenerated by scripts/export_stock_catalog.py). The dimensions
/// are factual product specifications from Zebra's media catalogs.
/// </summary>
public static class StockCatalog
{
    private const string ResourceName = "LabelForge.Core.Media.zebra-media-catalog.json";

    private static readonly Lazy<IReadOnlyList<StockMedia>> Loaded = new(Load);

    /// <summary>Every catalog entry, sorted by part number.</summary>
    public static IReadOnlyList<StockMedia> All => Loaded.Value;

    /// <summary>
    /// Case-insensitive search over part number, material, and size text.
    /// Every whitespace-separated term must match somewhere, so
    /// "4000d 50.8" narrows by material and size together.
    /// </summary>
    public static IReadOnlyList<StockMedia> Search(string query, int limit = 25)
    {
        string[] terms = SplitTerms(query);
        if (terms.Length == 0)
        {
            return [];
        }

        return All
            .Where(media => terms.All(term => Matches(media, term)))
            .Take(limit)
            .ToArray();
    }

    /// <summary>True when every term of the query matches this media; false for a
    /// blank query. The same rule <see cref="Search"/> applies, exposed so UI
    /// filter callbacks cannot drift from it.</summary>
    public static bool IsMatch(StockMedia media, string? query)
    {
        ArgumentNullException.ThrowIfNull(media);
        string[] terms = SplitTerms(query);
        return terms.Length > 0 && terms.All(term => Matches(media, term));
    }

    private static string[] SplitTerms(string? query) =>
        (query ?? string.Empty).Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);

    private static bool Matches(StockMedia media, string term) =>
        media.PartNumber.Contains(term, StringComparison.OrdinalIgnoreCase)
        || media.Material.Contains(term, StringComparison.OrdinalIgnoreCase)
        || media.SizeText.Contains(term, StringComparison.OrdinalIgnoreCase);

    private static IReadOnlyList<StockMedia> Load()
    {
        using Stream stream = typeof(StockCatalog).Assembly.GetManifestResourceStream(ResourceName)
            ?? throw new InvalidOperationException($"Embedded resource '{ResourceName}' is missing");
        var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
        return JsonSerializer.Deserialize<List<StockMedia>>(stream, options)
            ?? throw new InvalidOperationException("The media catalog resource deserialized to null");
    }
}
